### ISSUE TITLE
Include `dist` (Compiled Resources) in Releases.

### ISSUE THREAD

**Issue by amjad1233** [szimek/signature_pad#759]
**Do you want to request a feature or report a bug?**
Feature

**What is the current behaviour?**
No dist folder when downloading the version tarball ( i.e., https://github.com/szimek/signature_pad/archive/refs/tags/v4.1.7.zip )
It becomes especially challenging when the library is used in a larger ecosystem such as Drupal, not through a CDN but by downloading JS files directly. Previously we used to grab one from an example. 
i.e., "/libraries/signature_pad/example/js/signature_pad.js" 
See : This is blocking us updating library : https://www.drupal.org/project/webform/issues/3279896

**What is the expected behaviour?**
The files should come compiled i.e., npm run build should run before packaging the scripts.
something like `dist/signature_pad.js`

**Which versions of SignaturePad, and which browser / device are affected by this issue? Did this work in previous versions of SignaturePad?**
4.1.7

**Comment by amjad1233** [comment]
Hi @UziTech  thank you for your response. Some users prefer using the native Drupal [library](https://www.drupal.org/docs/develop/creating-modules/adding-assets-css-js-to-a-drupal-module-via-librariesyml) on via the server location instead of the CDN. If the `dist` is in the tarball, we can refer to that as a local path on the server. 

A quick POC : https://github.com/amjad1233/signature_pad/releases/tag/v4.1.7

Where we can use the library by siganture_pad/dist/signature_pad.min.js or something. 

As a workaround, we are using the library from your demo script: i.e., /signature_pad/docs/js/signature_pad.umd.js:

```
libraries.signature_pad:
  remote: https://github.com/szimek/signature_pad
  version: '4.1.7'
  license:
    name: MIT
    url: http://opensource.org/licenses/mit-license.php
    gpl-compatible: true
  directory: signature_pad
  cdn:
    /libraries/signature_pad/: https://cdn.jsdelivr.net/npm/signature_pad@4.1.7/dist/signature_pad.umd.min.js/
  js:
    /libraries/signature_pad/docs/js/signature_pad.umd.js: {}
    ```
